#!/bin/bash
PCAP_PATH=`find \`pwd\` -name $1`
echo "1: Registration
2: Establish
3: Service Request
"

echo -n "Input number:"
read num

case $num in
  1) tshark -r $PCAP_PATH -V 'nas_5gs.mm.message_type==0x41 && ngap.InitialUEMessage_element' | grep -A 10000 "NG Application Protocol" > registration_request.txt
     tshark -r $PCAP_PATH -V 'http2.header.value matches "post" && http2.header.value matches "auth"'  | grep -A 97 "HyperText Transfer Protocol 2" | head -n 98 > nausf_ueauthentication_request.txt
      STREAM_ID=`grep -e "Stream Identifier:" nausf_ueauthentication_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 12`
      STR1="http2.streamid == "
      STR2=' && json.key contains "Suci"'
      STR4="&& http2.header.value == 201 && !json"
      STR3=$STR1$STREAM_ID$STR2
      STR5=$STR1$STREAM_ID$STR4
     tshark -r $PCAP_PATH -V $STR3 | grep -A 100 "HyperText Transfer Protocol 2" | head -n 21 >> nausf_ueauthentication_request.txt
     tshark -r $PCAP_PATH -V $STR5 | grep -A 100 "HyperText Transfer Protocol 2" | head -n 55 > nausf_ueauthentication_response.txt
     tshark -r $PCAP_PATH -V 'nas_5gs.mm.message_type == 0x56' | grep -A 10000 "NG Application Protocol" > authentication_request.txt
    # Registration Request
    MESSAGE_TYPE_1=`grep -e "Message type:" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 3-4`
    RAN_UE_NGAP_ID_1=`grep -e "RAN-UE-NGAP-ID:" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 2`
    NAS_PDU_1=`grep -e "NAS-PDU:" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 2`
    TAC_1=`grep -e "tAC" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 2`
    MCC_1=`grep -e "MCC" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f6 | uniq | tr -d \( | tr -d \)`
    MNC_1=`grep -e "MNC" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f6 | uniq | tr -d \( | tr -d \)`
    CELL_1=`grep -e "nRCellIdentity" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f2`
    RRC_ES_CAUSE_1=`grep -e "RRCEstablishmentCause:" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f2`
    UE_CON_REQ_1=`grep -e "UEContextRequest:" registration_request.txt | sed 's/^[ \t]*//' | cut -d " " -f2`
    
    # Nausf_UEAuthentication_Authentication Request
    PATH_1=`grep -e "Header: :path:" nausf_ueauthentication_request.txt | sed 's/^[ \t]*//' | cut -d " " -f3`
    SUCI_1=`grep -e "suci-" nausf_ueauthentication_request.txt | sed 's/^[ \t]*//' | cut -d " " -f3`
    NETWORK_NAME_1=`grep -e "5G:" nausf_ueauthentication_request.txt | sed 's/^[ \t]*//' | cut -d " " -f3`
    
    # Nausf_UEAuthentication_Authentication Response
    STATUS_1=`grep -e "Header: :status:" nausf_ueauthentication_response.txt | sed 's/^[ \t]*//' | cut -d " " -f3-4`
    LOCATION_1=`grep -e "Header: location:" nausf_ueauthentication_response.txt | sed 's/^[ \t]*//' | cut -d " " -f3`

    # Authentication Request
    MESSAGE_TYPE_2=`grep -e "Message type:" authentication_request.txt | sed 's/^[ \t]*//' | cut -d " " -f 3-4`




     echo "
                    1. Registration Request(Initial UE Message)

+-------------------------------+----------+----------------------------------------------------+
| IE/Group Name                 | Presence | caputer                                            |
+-------------------------------+----------+----------------------------------------------------+
| Message Type                  | M        | $MESSAGE_TYPE_1                                     
+-------------------------------+----------+----------------------------------------------------+
| RAN UE NGAP ID                | M        | $RAN_UE_NGAP_ID_1                                   
+-------------------------------+----------+----------------------------------------------------+
| NAS-PDU                       | M        | $NAS_PDU_1      
+--------------------+----------+----------+----------------------------------------------------+
| User Location      | TAI      | M        | PLMN: $MCC_1$MNC_1 TAC: $TAC_1
| Information        +----------+----------+----------------------------------------------------+
|                    | NR CGI   | M        | PLMN: $MCC_1$MNC_1 CellID: $CELL_1
+--------------------+----------+----------+----------------------------------------------------+
| RRC Establishment Cause       | O        | $RRC_ES_CAUSE_1
+-------------------------------+----------+----------------------------------------------------+
| 5G-S-TMSI                     | O        |
+-------------------------------+----------+----------------------------------------------------+
| GUAMI                         | O        |
+-------------------------------+----------+----------------------------------------------------+
| AMF Set ID                    | O        |
+-------------------------------+----------+----------------------------------------------------+
| UE Context Request            | O        | $UE_CON_REQ_1
+-------------------------------+----------+----------------------------------------------------+

 UE(RAN)    AMF        AUSF       UDM
  |          |          |          |
  |    ●     |          |          |           
  |--------->|          |          |
  |          |          |          |
  |          |          |          | 
  |          |          |          | 

                    2. Nausf_UEAuthentication_Authentication Request

+-------------------------------+----------+----------------------------------------------------+
| Key                           | Presence | caputer                                            |
+-------------------------------+----------+----------------------------------------------------+
| Path                          | M        | $PATH_1                                           
+-------------------------------+----------+----------------------------------------------------+
| supiOrSuci                    | M        | $SUCI_1                                             
+-------------------------------+----------+----------------------------------------------------+
| servingNetworkName            | M        | $NETWORK_NAME_1                                             
+-------------------------------+----------+----------------------------------------------------+
| resynchronizationInfo         | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+
| pei                           | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+
| traceData                     | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+
| udmGroupId                    | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+
| routingIndicator              | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+
| cagId                         | O        |                                                    
+-------------------------------+----------+----------------------------------------------------+

 UE(RAN)    AMF        AUSF       UDM
  |          |          |          |
  |          |          |          |           
  |--------->|    ●     |          |
  |          |--------->|          |
  |          |          |          | 
  |          |          |          | 

                    3. Nausf_UEAuthentication_Authentication Response

+-------------------------------+----------+----------------------------------------------------+
| Key                           | Presence | caputer                                            |
+-------------------------------+----------+----------------------------------------------------+
| Status                        | M        | $STATUS_1                                           
+-------------------------------+----------+----------------------------------------------------+
| Location                      | M        | $LOCATION_1                                           
+-------------------------------+----------+----------------------------------------------------+

UE(RAN)    AMF        AUSF       UDM
  |          |          |          |
  |          |          |          |           
  |--------->|          |          |
  |          |--------->|          |
  |          |    ●     |          | 
  |          |<---------|          | 
  |          |          |          |
  |          |          |          |
  |          |          |          |

                    4. Authentication Request(Downlink NAS Transport)

+-------------------------------+----------+----------------------------------------------------+
| IE/Group Name                 | Presence | caputer                                            |
+-------------------------------+----------+----------------------------------------------------+
| Message Type                  | M        | $MESSAGE_TYPE_2                               
+-------------------------------+----------+----------------------------------------------------+
| AMF UE NGAP ID                | M        |                                  
+-------------------------------+----------+----------------------------------------------------+
| RAN UE NGAP ID                | M        |                                  
+-------------------------------+----------+----------------------------------------------------+
| Old AMF                       | O        |                                  
+-------------------------------+----------+----------------------------------------------------+
| RAN Paging Priority           | O        |                                  
+-------------------------------+----------+----------------------------------------------------+
| NAS-PDU                       | M        |                                  
+-------------------------------+----------+----------------------------------------------------+
| Mobility Restriction List     | O        |                                  
+-------------------------------+----------+----------------------------------------------------+
| Index to RAT/Frequency        | O        |                                  
| Selection Priority            |          |
+-------------------------------+----------+----------------------------------------------------+
| UE Aggregate Maximum Bit Rate | O        |                                  
+-------------------------------+----------+----------------------------------------------------+

UE(RAN)    AMF        AUSF       UDM
  |          |          |          |
  |          |          |          |           
  |--------->|          |          |
  |          |--------->|          |
  |          |          |          | 
  |    ●     |<---------|          | 
  |<---------|          |          |
  |          |          |          |
  |          |          |          |




"                           ;;
  2) tshark -r $PCAP_PATH 'http2'
esac
